services:
  db:
    image: postgres:16
    container_name: poke_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: poke_users
    volumes:
      - pokeapp_pokeapp_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: ${DOCKERHUB_USER}pokeapp-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: poke_backend
    restart: unless-stopped
    pull_policy: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=admin
      - DB_NAME=poke_users
    command: ["node", "wait-server.js"]

  frontend:
    image: ${DOCKERHUB_USER}pokeapp-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: poke_frontend
    restart: unless-stopped
    pull_policy: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pokeapp_pokeapp_db_data:
